name: webblen
description: Official Webblen Application

version: 5.8.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Firestore Dependencies
  cloud_firestore: ^0.11.0+2
  firebase_storage: ^3.0.0
  firebase_auth: ^0.11.1
  firebase_messaging: ^5.0.1+1
  firebase_dynamic_links: ^0.4.0
  cloud_functions: ^0.4.0+2

  #Social Dependencies
  flutter_facebook_login:
    git: https://github.com/roughike/flutter_facebook_login.git
#  flutter_twitter_login:
#      git: https://github.com/eudangeld/flutter_twitter_login.git

  #Location Dependencies
  location: ^2.3.5
  geoflutterfire: ^2.0.3+4
  geocoder: ^0.1.2
  flutter_google_places:
      git: https://github.com/mukai154/flutter_google_places.git
  google_maps_webservice: ^0.0.13

  #Image Dependencies
  cached_network_image: 0.8.0
  image_cropper: ^1.0.2
  image_picker: ^0.6.0+8
  flutter_image_compress: ^0.5.1

  #Phone Util Dependencies
  flutter_local_notifications: ^0.7.1+1
  url_launcher: ^5.0.2
  contact_picker: ^0.0.2
  share: ^0.6.1+1
  flutter_sms: ^1.0.1
  add_2_calendar: ^1.2.2

  #Date Time Dependencies
  table_calendar: 1.2.2
  flutter_picker: ^1.0.11
  flutter_native_timezone: ^1.0.4

  #Other Dependencies
  font_awesome_flutter: 8.4.0
  flutter_tags: ^0.3.1
  carousel_slider: ^1.3.0
  liquid_pull_to_refresh: ^1.1.1
  shimmer: ^1.0.0
  hidden_drawer_menu:  ^1.0.1
  flutter_masked_text: ^0.8.0
  flushbar: 1.5.0
  animated_text_kit: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
      - family: Helvetica Neue
        fonts:
          - asset: assets/fonts/HelveticaNeueThin.ttf
            weight: 300
          - asset: assets/fonts/HelveticaNeueLight.ttf
            weight: 400
          - asset: assets/fonts/HelveticaNeue.ttf
            weight: 500
          - asset: assets/fonts/HelveticaNeueMedium.ttf
            weight: 600
          - asset: assets/fonts/HelveticaNeueBold.ttf
            weight: 700